import type { Metadata } from 'next';
import { Poppins, Outfit } from 'next/font/google';

import './globals.scss';
import { StoreProvider } from './store/StoreProvider';

const poppins = Poppins({
  variable: '--default-font-family',
  weight: ['400', '500', '600', '700', '800'],
  subsets: ['latin'],
});

const outfit = Outfit({
  variable: '--accent-font-family',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${outfit.variable} antialiased`}>
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
