import type { Metadata } from 'next';
import { Poppins, Outfit } from 'next/font/google';
import { getMessages, setRequestLocale } from 'next-intl/server';
import { NextIntlClientProvider } from 'next-intl';
import { FC, PropsWithChildren } from 'react';

import '../globals.scss';
import { NextIntlUseClientFallbackProvider } from '@/src/providers/NextIntlUseClientFallbackProvider';
import { StoreProvider } from '@/src/store/StoreProvider';

const poppins = Poppins({
  variable: '--default-font-family',
  weight: ['400', '500', '600', '700', '800'],
  subsets: ['latin'],
});

const outfit = Outfit({
  variable: '--accent-font-family',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface Props extends PropsWithChildren {
  params: Promise<{ locale: string }>;
}

const RootLayout: FC<Props> = async (props) => {
  const params = await props.params;
  const { children } = props;

  setRequestLocale(params.locale);

  const messages = await getMessages();

  return (
    <html lang={params.locale}>
      <body className={`${poppins.variable} ${outfit.variable} antialiased`}>
        <NextIntlClientProvider messages={messages}>
          <NextIntlUseClientFallbackProvider>
            <StoreProvider>{children}</StoreProvider>
          </NextIntlUseClientFallbackProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
};

export default RootLayout;
